### ISSUE TITLE
Promote _supported_pairs to public method

### ISSUE THREAD

**Issue by bebosudo** [Crypto-toolbox/bitex#149]
Is there any reason the `_supported_pairs` method of exchanges is "private" (and e.g. not showing up in the docs).
PR #127 should have provided the pairs of all the exchanges implemented.

**Comment by nlsdfnbch** [comment]
Because it's a property:
https://github.com/Crypto-toolbox/bitex/blob/e95c75272b24ab19eb3cb40d6083dea87be6b8c7/bitex/interface/base.py#L31

That way, we could later on convert them to pair formatters, instead of lists if we wanted to do so and only have to change the property. At least I think that was my reasoning behind it.

**Comment by bebosudo** [comment]
Okay, thanks for the clarification ;-)
