### ISSUE TITLE
Joining forces with mexbtcapi

### ISSUE THREAD

**Issue by goncalopp** [Crypto-toolbox/bitex#150]
Hi,
I'm the main author of [mexbtcapi](https://github.com/goncalopp/mexbtcapi), a framework somewhat similar to bitex.

I was thinking of simply adding bitex as a dependency to mexbtcapi, but since it seems like you're still working on higher-level interfaces, I though I should give you a heads-up

Mexbtcapi was developed top-down - starting from well tested high-level interfaces. The interfaces are significantly higher-level than bitex's, but it doesn't support many exchanges at the moment.

While I only started reading it today, it looks to me like bitex was developed bottom-up - starting from exchange API implementations. Its higher level interfaces seem a bit lacking. 

For example, it seems (please correct me if I'm wrong) that I cannot get a list of all the exchanges that trade, say, litecoin. Or get a list of realtime tickers for all BTC/XMR tickers on all exchanges, if they don't have the same pair string representation. These are operations that are quite easy in mexbtcapi (see [demo folder](https://github.com/goncalopp/mexbtcapi/tree/master/demo)), so I wanted to ask you if you think it might make sense to somehow merge the projects.

**Comment by nlsdfnbch** [comment]
Ahoi @goncalopp! 

You're correct - there's no way to get real-time data via bitex. That's because it is purely designed to be a REST api wrapper. The interfaces only expose the functions all exchanges have in common, with a unified method signature.

All in all,  bitex is meant to be a bit more low level and basic -  that's because from my experience,  more sophisticated frameworks rarely fit the needs of the user 100%, and need adjusting anyway. That's why features such as formatted responses are optional in my library. 

You are,  of course,  welcome to make use of bitex - I'd suggest using the dev branch though,  since the next release will be a complete rewrite of the library and quite incompatible with the current release. 

Cheers, 

Nils

**Comment by goncalopp** [comment]
Hi Nils,
Thanks for the tip! I'll take a look into integrating the dev branch into mexbtcapi then

Quick question: there seem to be no WSS interfaces on dev - is that on purpose?

Thanks, and keep up the great work!

**Comment by nlsdfnbch** [comment]
Yes,  that's on purpose. Like I said,  it's meant to be a REST wrapper,  the websocket clients were experimental (and very buggy) . They're planned to be added down the road sometime,  but have no set ETA!
